

# Setup
title: exploringintent
description: Capturing life's moments through the lens of a curious explorer, one pixel at a time
url: https://exploringintent.github.io/
domain: exploringintent.github.io
paginate: 5
theme: null


github:
    is_user_page: true
    owner_url: https://github.com/exploringintent
    owner_name: Janis Bruzans

# Gems
plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - scripts/
  - vendor/

sass:
  sass_dir: _sass
  style: compressed
    


# Optimize Jekyl SEO Tag
logo: logo.png
social:
  name: Janis Bruzans
  links:
    - https://github.com/exploringintent
    - https://www.instagram.com/exploringintent/
    - https://www.linkedin.com/in/janisbruzans
lang: en-US

# Specify the author for blog posts
author:
  name: Janis Bruzans
  url: https://www.linkedin.com/in/janisbruzans